language: python
python:
#  - "2.7"
  - "3.6"
  - "3.7-dev"

sudo: false


install:
  - python --version
  - pip install hisparc-sapphire

script:
  - python -c "import sapphire; sapphire.run_tests()"
